---
name: validate pr review
on:
  pull_request_review:
    types:
      - submitted
      - dismissed
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      pull-requests: write
      contents: read
    steps:
      - run: "true"
        env:
          EVENT: ${{ toJson(github.event) }}
      - uses: suzuki-shunsuke/validate-pr-review-action@latest
        with:
          pull_request_number: ${{ github.event.pull_request.number }}
