---
name: validate pr review
on:
  pull_request_review:
    types:
      - submitted
      - dismissed
jobs:
  validate-pr-review:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: suzuki-shunsuke/validate-pr-review-action@pr/21
