---
name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - run: gh -R "$GITHUB_REPOSITORY" pr review "$NUMBER" -a
        env:
          GH_TOKEN: ${{ github.token }}
          NUMBER: ${{ github.event.number }}
